features:
  - all_area
  - area
  - area_diff_all_area
  - area_div_all_area
  - build_year
  - building_to_land_ratio
  - building_to_land_ratio_diff_capacity_ratio
  - building_to_land_ratio_div_capacity_ratio
  - capacity_ratio
  - circumstances
  - city_name
  - city_planning
  - direction
  - distance_from_tokyo_station
  - distance_minutes
  - estimated_land_price
  - feature_purpose
  - frontage
  - land_shape
  - land_type
  - land_unit_price
  - layout
  - load_type
  - load_width
  - purpose
  - region
  - region_code
  - renovation
  - station_name
  - structure
  - te_city_name
  - te_city_planning
  - te_direction
  - te_feature_purpose
  - te_land_shape
  - te_land_type
  - te_load_type
  - te_region
  - te_region_code
  - te_renovation
  - te_station_name
  - te_structure
  - te_town_name
  - town_name
  - trade_quater
  - trade_quater_diff_build_year
  - trade_year
  - trade_year_diff_build_year
  - year_name
