common:
    seed: &seed 2025
    metrics:
        name: rmsle
        params: {}
    drop:
        - large_diff2
    kaggle:
        submit: False

data:
    loader:
        train:
            data_type: train
            reduce: False
        test:
            data_type: test
            reduce: False
    features:
        name: custom_007
        cat_features:
        oof:
            name:
    target:
        name: y
        convert_type: log1p
        reconvert_type: expm1
    adversarial_validation: False

validation:
    name: StratifiedKFold
    params:
        n_splits: 5
        shuffle: True
        random_state: *seed
    split:
        y: city_name
        groups:
    weight:
        - 0.2
    single: False

model:
    name: catboost
    task_type: regression
    params:
        loss_function: RMSE
        eval_metric: RMSE
        learning_rate: 0.1
        iterations: 10000
        random_seed: *seed
        od_type: Iter
        depth: 6
        task_type: CPU
    iterations: 10000
    verbose_eval: 200
    early_stopping_rounds: 200
    imp_type: total_gain