common:
    seed: &seed 2022
    metrics:
        name: rmsle
        params: {}
    drop:
        - large_diff2
    kaggle:
        submit: False

data:
    dir: ../data/input
    loader:
        train:
            data_type: train
            reduce: False
        test:
            data_type: test
            reduce: False
    features:
        name: custom_007
        cat_features:
        oof:
            name:
    target:
        name: y
        convert_type: log1p
        reconvert_type: expm1
    adversarial_validation: False

validation:
    name: StratifiedKFold
    params:
        n_splits: 5
        shuffle: True
        random_state: *seed
    split:
        y: city_name
        groups:
    weight:
        - 0.2
    single: False

model:
    name: lightgbm
    task_type: regression
    params:
        boosting_type: gbdt
        objective: regression
        metric: rmse
        learning_rate: 0.1
        num_leaves: 70
        min_child_samples: 20
        feature_fraction: 0.4
        bagging_fraction: 1.0
        lambda_l1: 4.766061358445339
        lambda_l2: 0.0
        max_bin: 255
        verbose: -1
        nthread: -1
        seed: *seed
        first_metric_only: True
    num_boost_round: 10000
    verbose_eval: 200
    early_stopping_rounds: 200
    imp_type: gain